import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavLink } from "./lib/components/navbar";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="has-background-dark	p-5 has-text-white-ter	">
          <div className="navbar-start">
            <NavLink
              href='/'
              className="navbar-item ">
              Signup
            </NavLink>
            <NavLink
              href="/login"
              className="navbar-item">
              Login
            </NavLink>
          </div>
        </nav>
      <div className="p-5 is-color-white">
          {children}
        </div>
      </body>
    </html>
  );
}
